version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13-alpine
    container_name: bandflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bandflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # Redis for caching and session management
  redis:
    image: redis:6-alpine
    container_name: bandflow-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  # Backend API Server
  server:
    build: ./server
    container_name: bandflow-server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bandflow
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your_jwt_secret_here
    networks:
      - app-network
    restart: unless-stopped

  # Frontend Client
  client:
    build: ./client
    container_name: bandflow-client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: